LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := PocoFoundation
LOCAL_SRC_FILES := ../lib/android/$(TARGET_ARCH_ABI)/libPocoFoundation.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/../include
include $(PREBUILT_STATIC_LIBRARY)

LOCAL_MODULE := PocoNet
LOCAL_SRC_FILES := ../lib/android/$(TARGET_ARCH_ABI)/libPocoNet.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/../include
include $(PREBUILT_STATIC_LIBRARY)

LOCAL_MODULE := PocoUtil
LOCAL_SRC_FILES := ../lib/android/$(TARGET_ARCH_ABI)/libPocoUtil.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/../include
include $(PREBUILT_STATIC_LIBRARY)

LOCAL_MODULE := PocoXML
LOCAL_SRC_FILES := ../lib/android/$(TARGET_ARCH_ABI)/libPocoXML.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/../include
include $(PREBUILT_STATIC_LIBRARY)

LOCAL_MODULE := PocoZip
LOCAL_SRC_FILES := ../lib/android/$(TARGET_ARCH_ABI)/libPocoZip.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/../include
include $(PREBUILT_STATIC_LIBRARY)

LOCAL_MODULE := PocoData
LOCAL_SRC_FILES := ../lib/android/$(TARGET_ARCH_ABI)/libPocoData.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/../include
include $(PREBUILT_STATIC_LIBRARY)

LOCAL_MODULE := PocoDataSQLite
LOCAL_SRC_FILES := ../lib/android/$(TARGET_ARCH_ABI)/libPocoDataSQLite.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/../include
include $(PREBUILT_STATIC_LIBRARY)

LOCAL_MODULE := PocoCrypto
LOCAL_SRC_FILES := ../lib/android/$(TARGET_ARCH_ABI)/libPocoCrypto.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/../include
include $(PREBUILT_STATIC_LIBRARY)

LOCAL_MODULE := PocoNetSSL
LOCAL_SRC_FILES := ../lib/android/$(TARGET_ARCH_ABI)/libPocoNetSSL.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/../include
include $(PREBUILT_STATIC_LIBRARY)

LOCAL_MODULE := ssl
LOCAL_SRC_FILES := ../lib/android/$(TARGET_ARCH_ABI)/libssl.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/../include
include $(PREBUILT_STATIC_LIBRARY)

LOCAL_MODULE := crypto
LOCAL_SRC_FILES := ../lib/android/$(TARGET_ARCH_ABI)/libcrypto.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/../include
include $(PREBUILT_STATIC_LIBRARY)
